# Generated by Django 6.0.7 on 2026-08-12 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('target_type', models.CharField(choices=[('general', 'General'), ('building', 'Por edificio'), ('resident', 'Para residente')], default='general', max_length=30)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='structure.garden')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Communications',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['garden'], name='communicati_garden__b4d923_idx'), models.Index(fields=['published_at'], name='communicati_publish_97ef5c_idx')],
            },
        ),
    ]
