# Generated by Django 6.1.1 on 2026-09-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_period_alter_payment_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='charge_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='concept',
            field=models.CharField(choices=[('maintenance', 'Mantenimiento'), ('extraordinary', 'Cuota extraordinaria'), ('reservation', 'Reserva'), ('parking', 'Parqueo'), ('services', 'Servicios'), ('other', 'Otro')], default='other', max_length=50),
        ),
        migrations.DeleteModel(
            name='ChargeType',
        ),
    ]
