# Generated by Django 6.1.1 on 2026-09-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0003_alter_residencial_rnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencial',
            name='distribucion',
            field=models.CharField(blank=True, choices=[('torres', 'Torres'), ('edificios', 'Edificios')], max_length=20, verbose_name='Distribución'),
        ),
    ]
