# Generated by Django 6.1.1 on 2026-09-13 20:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('structure', '0003_apartment_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept', models.CharField(choices=[('maintenance', 'Mantenimiento'), ('security', 'Seguridad'), ('cleaning', 'Limpieza'), ('administration', 'Administración'), ('reserve_fund', 'Fondo de reserva'), ('water', 'Agua'), ('electricity', 'Electricidad'), ('other', 'Otro')], max_length=30)),
                ('periodicity', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('photo', models.FileField(blank=True, null=True, upload_to='mantenimiento/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cargos de mantenimiento',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='maintenanceorder',
            name='maintenance_status_df8fba_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceorder',
            name='maintenance_assigne_34d235_idx',
        ),
        migrations.AddField(
            model_name='maintenancecharge',
            name='apartments',
            field=models.ManyToManyField(blank=True, related_name='maintenance_charges', to='structure.apartment'),
        ),
        migrations.DeleteModel(
            name='MaintenanceOrder',
        ),
    ]
