# Generated by Django 6.1.1 on 2026-09-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_maintenancecharge_apartments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancecharge',
            name='payment_methods',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('check', 'Cheque'), ('online', 'Pago en línea'), ('other', 'Otro')], max_length=20, null=True),
        ),
    ]
