# Generated by Django 6.1.1 on 2026-09-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenancecharge_payment_methods'),
        ('structure', '0004_owner_to_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecharge',
            name='apartment',
            field=models.ForeignKey(blank=True, help_text='Vacío = aplica a todos los departamentos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_charges', to='structure.apartment', verbose_name='Departamento (si es aplicable)'),
        ),
    ]
