# Generated by Django 6.1.1 on 2026-09-14 00:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('structure', '0003_apartment_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('certificado', 'Certificado'), ('permiso', 'Permiso'), ('mantenimiento', 'Mantenimiento'), ('instalacion', 'Instalación'), ('reparacion', 'Reparación'), ('documentacion', 'Documentación'), ('otro', 'Otro')], max_length=30)),
                ('description', models.TextField()),
                ('request_date', models.DateField(default=django.utils.timezone.localdate)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='solicitudes/')),
                ('tracking_response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='structure.apartment')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='residents.resident')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['apartment', 'status'], name='solicitudes_apartme_4236c9_idx'), models.Index(fields=['status'], name='solicitudes_status_b2474e_idx')],
            },
        ),
    ]
