# Generated by Django 6.0.7 on 2026-08-12 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_areas', to='structure.garden')),
            ],
            options={
                'verbose_name_plural': 'Common Areas',
                'ordering': ['garden', 'name'],
                'unique_together': {('garden', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('expected_guests', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_approved', to=settings.AUTH_USER_MODEL)),
                ('common_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.commonarea')),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['common_area', 'start_time'], name='reservation_common__245ce5_idx'), models.Index(fields=['reserved_by'], name='reservation_reserve_9d6574_idx'), models.Index(fields=['status'], name='reservation_status_f1a03a_idx')],
                'constraints': [models.UniqueConstraint(fields=('common_area', 'start_time', 'end_time'), name='unique_reservation_time')],
            },
        ),
    ]
