# Generated by Django 6.1.1 on 2026-09-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('residents', '0001_initial'),
        ('structure', '0003_apartment_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='structure.apartment'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='residents.resident'),
        ),
    ]
