# Generated by Django 6.1.1 on 2026-09-13 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas_comunes', '0002_alter_areacomun_available_from_and_more'),
        ('reservations', '0002_reservation_apartment_reservation_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='common_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='areas_comunes.areacomun'),
        ),
    ]
