# Generated by Django 6.1.1 on 2026-09-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='category',
            field=models.CharField(choices=[('aviso', 'Aviso'), ('mantenimiento', 'Mantenimiento'), ('evento', 'Evento'), ('seguridad', 'Seguridad'), ('piscinas', 'Piscinas'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='communication',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='comunicados/'),
        ),
    ]
