# Generated by Django 6.1.1 on 2026-09-12 00:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('residents', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-period'], 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_due_dat_752274_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='residents.resident'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='structure.apartment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['period'], name='payments_pa_period_c8a744_idx'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_number',
        ),
    ]
