# Generated by Django 6.1.1 on 2026-09-12 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_and_more'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='residents.resident'),
        ),
    ]
