# Generated by Django 6.1.1 on 2026-09-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_charge_type_payment_concept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='concept',
            field=models.CharField(choices=[('maintenance', 'Mantenimiento'), ('extraordinary', 'Cuota extraordinaria'), ('reservation', 'Reserva'), ('parking', 'Parqueo'), ('services', 'Servicios'), ('other', 'Otro')], max_length=50),
        ),
    ]
