# Generated by Django 6.0.7 on 2026-08-12 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_apartment', models.CharField(choices=[('owner', 'Propietario'), ('occupant', 'Ocupante')], default='occupant', max_length=30)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='structure.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Residents',
                'ordering': ['apartment', '-move_in_date'],
                'indexes': [models.Index(fields=['apartment'], name='residents_r_apartme_fccdaf_idx'), models.Index(fields=['user'], name='residents_r_user_id_3e547b_idx')],
                'unique_together': {('user', 'apartment')},
            },
        ),
    ]
