# Generated by Django 6.1 on 2026-09-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='mascotas',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='resident',
            name='tipo_relacion',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino'), ('familiar', 'Familiar'), ('ocupante', 'Ocupante')], default='ocupante', max_length=30),
        ),
    ]
