# Generated by Django 4.2.8 on 2026-08-11 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Gardens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('number_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='structure.garden')),
            ],
            options={
                'verbose_name_plural': 'Buildings',
                'ordering': ['garden', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('type', models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('commercial', 'Local comercial')], default='apartment', max_length=30)),
                ('status', models.CharField(choices=[('empty', 'Vacío'), ('occupied', 'Ocupado'), ('maintenance', 'En reparación'), ('blocked', 'Bloqueado')], default='empty', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='structure.building')),
            ],
            options={
                'verbose_name_plural': 'Apartments',
                'ordering': ['building', 'floor', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['garden'], name='structure_b_garden__8ad1c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('garden', 'name')},
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['building'], name='structure_a_buildin_782e02_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['status'], name='structure_a_status_034e1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('building', 'number')},
        ),
    ]
