# Generated by Django 6.1.1 on 2026-09-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='document_image',
            field=models.FileField(blank=True, null=True, upload_to='visitantes/'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='document_type',
            field=models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('licencia', 'Licencia de conducir'), ('otro', 'Otro')], max_length=20, null=True),
        ),
    ]
