# Generated by Django 6.1.1 on 2026-09-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0002_alter_residencial_rnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencial',
            name='rnc',
            field=models.CharField(blank=True, max_length=11, verbose_name='RNC'),
        ),
    ]
