# Generated by Django 6.1.1 on 2026-09-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0005_alter_residencial_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencial',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, verbose_name='Teléfono de administración'),
        ),
    ]
