# Generated by Django 4.2.8 on 2026-08-11 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('document', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('family', 'Familiar'), ('delivery', 'Delivery'), ('technician', 'Técnico'), ('provider', 'Proveedor'), ('other', 'Otro')], default='other', max_length=30)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('scheduled_entry', models.DateTimeField()),
                ('scheduled_exit', models.DateTimeField(blank=True, null=True)),
                ('actual_entry', models.DateTimeField(blank=True, null=True)),
                ('actual_exit', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Esperando'), ('authorized', 'Autorizado'), ('rejected', 'Rechazado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='structure.apartment')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_authorized', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visitors',
                'ordering': ['-scheduled_entry'],
                'indexes': [models.Index(fields=['apartment'], name='visitors_vi_apartme_acc525_idx'), models.Index(fields=['scheduled_entry'], name='visitors_vi_schedul_f9d8e5_idx'), models.Index(fields=['status'], name='visitors_vi_status_9b5b9b_idx')],
            },
        ),
    ]
