# Generated by Django 6.1.1 on 2026-10-05 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modelo', models.CharField(choices=[('gpt', 'GPT · OpenAI'), ('claude', 'Claude · Anthropic'), ('gemini', 'Gemini · Google'), ('llama', 'Llama · Meta'), ('mistral', 'Mistral AI'), ('deepseek', 'DeepSeek'), ('grok', 'Grok · xAI')], default='gpt', max_length=20, verbose_name='Modelo')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integración AI',
                'verbose_name_plural': 'Integración AI',
            },
        ),
    ]
