# Generated by Django 6.1.1 on 2026-10-05

from django.db import migrations, models


def ajustar_modelos(apps, schema_editor):
    """El campo `modelo` guardaba el proveedor: se mueve a `proveedor` por el
    renombre y se asigna el primer modelo de visión de cada proveedor."""
    IntegracionIA = apps.get_model('configuracion', 'IntegracionIA')
    modelos = {
        'gpt': 'gpt-4o',
        'claude': 'claude-sonnet-4-20250514',
        'gemini': 'gemini-2.0-flash',
        'mistral': 'pixtral-12b-2409',
        'grok': 'grok-2-vision-1212',
    }
    for integracion in IntegracionIA.objects.all():
        integracion.modelo = modelos.get(integracion.proveedor, '')
        integracion.save(update_fields=['modelo'])


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integracionia',
            old_name='modelo',
            new_name='proveedor',
        ),
        migrations.AlterField(
            model_name='integracionia',
            name='proveedor',
            field=models.CharField(choices=[('gpt', 'GPT · OpenAI'), ('claude', 'Claude · Anthropic'), ('gemini', 'Gemini · Google'), ('llama', 'Llama · Meta'), ('mistral', 'Mistral AI'), ('deepseek', 'DeepSeek'), ('grok', 'Grok · xAI')], default='gpt', max_length=20, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='integracionia',
            name='modelo',
            field=models.CharField(default='gpt-4o', max_length=60, verbose_name='Modelo'),
        ),
        migrations.RunPython(ajustar_modelos, migrations.RunPython.noop),
    ]
