# Generated by Django 6.1.1 on 2026-10-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_alter_integracionia_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracionia',
            name='proveedor',
            field=models.CharField(choices=[('gpt', 'GPT · OpenAI'), ('claude', 'Claude · Anthropic'), ('gemini', 'Gemini · Google'), ('llama', 'Llama · Meta'), ('mistral', 'Mistral AI'), ('deepseek', 'DeepSeek'), ('grok', 'Grok · xAI')], default='gpt', max_length=20, verbose_name='Proveedor'),
        ),
    ]
