# Generated by Django 6.1 on 2026-08-20 19:14

import django.db.models.deletion
from django.db import migrations, models


def copy_incident_images(apps, schema_editor):
    Incident = apps.get_model('incidents', 'Incident')
    IncidentImage = apps.get_model('incidents', 'IncidentImage')
    for incident in Incident.objects.exclude(image_urls=None):
        for url in incident.image_urls or []:
            if isinstance(url, str) and url:
                IncidentImage.objects.get_or_create(incident_id=incident.pk, url=url)


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='incidents.incident')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('incident', 'url'), name='unique_incident_image_url')],
            },
        ),
        migrations.RunPython(
            code=copy_incident_images,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='incident',
            name='image_urls',
        ),
    ]
