# Generated by Django 6.1.1 on 2026-09-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='garden_id',
            new_name='garden',
        ),
    ]
