# Generated by Django 6.1.1 on 2026-09-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Encargado de Administración'), ('resident', 'Residente'), ('propietario', 'Propietario'), ('maintenance', 'Personal de Mantenimiento'), ('security', 'Seguridad/Portería')], default='resident', max_length=30),
        ),
    ]
