# Generated by Django 6.1.1 on 2026-10-09 14:25

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[accounts.validators.validar_cedula]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[accounts.validators.validar_telefono]),
        ),
    ]
