# Generated by Django 6.1.1 on 2026-09-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas_comunes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='available_until',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
