# Generated by Django 6.1 on 2026-09-14 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0002_migrar_duenos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='propietario',
            index=models.Index(fields=['user'], name='propietario_user_id_dac8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='propietario',
            index=models.Index(fields=['cedula'], name='propietario_cedula_b1f882_idx'),
        ),
    ]
