# Generated by Django 6.1.1 on 2026-10-09 14:25

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0003_propietario_propietario_user_id_dac8d0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, validators=[accounts.validators.validar_cedula]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[accounts.validators.validar_contacto_emergencia]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='phone',
            field=models.CharField(max_length=14, validators=[accounts.validators.validar_telefono]),
        ),
    ]
