# Generated by Django 6.0.7 on 2026-08-12 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('preventive', 'Preventivo'), ('corrective', 'Correctivo'), ('emergency', 'Emergencia')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=30)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_orders', to='structure.apartment')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_orders', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_orders', to='incidents.incident')),
            ],
            options={
                'verbose_name_plural': 'Maintenance Orders',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['status'], name='maintenance_status_df8fba_idx'), models.Index(fields=['assigned_to'], name='maintenance_assigne_34d235_idx')],
            },
        ),
    ]
