# Generated by Django 6.1.1 on 2026-09-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancecharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancecharge',
            name='apartments',
        ),
        migrations.AddField(
            model_name='maintenancecharge',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
