# Generated by Django 6.1.1 on 2026-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Encargado de Administración'), ('resident', 'Residente'), ('propietario', 'Propietario'), ('security', 'Seguridad/Portería')], default='resident', max_length=30),
        ),
    ]
