# Generated by Django 6.1.1 on 2026-09-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_apartment_renames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['building', 'floor', 'name'], 'verbose_name_plural': 'Apartments'},
        ),
    ]
