# Generated by Django 6.1.1 on 2026-09-13 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('area_type', models.CharField(choices=[('gazebo', 'Gazebo'), ('salon_eventos', 'Salón de eventos'), ('area_social', 'Área social'), ('piscina', 'Piscina'), ('cancha_deportiva', 'Cancha deportiva'), ('gimnasio', 'Gimnasio'), ('zona_parrillas', 'Zona de parrillas'), ('otro', 'Otro')], max_length=30)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('available_days', models.CharField(choices=[('todos', 'Todos los días'), ('lun_vie', 'Lunes a Viernes'), ('fines_semana', 'Fines de semana'), ('personalizado', 'Personalizado')], max_length=20)),
                ('usage_conditions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En mantenimiento')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Áreas Comunes',
                'ordering': ['name'],
            },
        ),
    ]
