# Generated by Django 6.1 on 2026-08-20 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_chat_groups(apps, schema_editor):
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    ChatGroup = apps.get_model('chat', 'ChatGroup')
    for message in ChatMessage.objects.exclude(group_name__isnull=True).exclude(group_name=''):
        group, _ = ChatGroup.objects.get_or_create(name=message.group_name)
        ChatMessage.objects.filter(pk=message.pk).update(group_id=group.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_chatme_group_n_c4ed4a_idx',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.chatgroup'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['group'], name='chat_chatme_group_i_d54aba_idx'),
        ),
        migrations.RunPython(
            code=copy_chat_groups,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='group_name',
        ),
    ]
