# Generated by Django 6.1.1 on 2026-09-13 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_incident_image_urls_incidentimage'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='incidentes/evidencia/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='incident',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='residents.resident'),
        ),
    ]
